In [23]:
import pandas as pd
import numpy as np


def load_data(url, ):
    return pd.read_csv(url)


def clean_tiobe_top_20(df):
    return df.rename(columns=lambda col: col.replace("Sept", "Rank"))


def clean_tiobe_history(df):
    return (
        df
        .drop(columns=['-'])
        .set_index('Programming Language')
        .transpose()
        .rename_axis('', axis='columns')
        .reset_index()
        .rename(columns={'index': 'year'})
        .melt(id_vars='year')
        .rename(columns={'value': 'rank', '': 'language'})
        .sort_values(by=['year', 'rank'])
        .assign(rank=lambda df: df['rank'].replace({'-': np.nan}).astype('float'))
        .query("~language.isin(['Pascal', 'Visual Basic', '(Visual) Basic', 'Prolog'])", engine='python')
    )

tiobe_top_20_url = "https://raw.githubusercontent.com/mwiemers/python_presessional_app/main/tiobe_top20.csv"
tiobe_history_url = "https://raw.githubusercontent.com/mwiemers/python_presessional_app/main/tiobe_history.csv"
gapminder_url = "https://raw.githubusercontent.com/mwiemers/python_workshops_app/main/gapminder.csv"

df = pd.read_csv(tiobe_top_20_url)

In [24]:
df

   Sep 2024\tSep 2023\tProgramming Language\tRatings\tChange
0                     1\t1\t-\tPython\t20.17%\t+6.01%
1                        2\t3\t^\tC++\t10.75%\t+0.09%
2                       3\t4\t^\tJava \t9.45%\t-0.04%
3                           4\t2\tv\tC\t8.89%\t-2.38%
4                         5\t5\t-\tC# \t6.08%\t-1.22%
5                  6\t6\t-\tJavaScript\t3.92%\t+0.62%
6                7\t7\t-\tVisual Basic\t2.70%\t+0.48%
7                        8\t12\t^^\tGo\t2.35%\t+1.16%
8                        9\t10\t^\tSQL\t1.94%\t+0.50%
9                   10\t11\t^\tFortran\t1.78%\t+0.49%
10    11\t15\t^^\tDelphi/Object Pascal\t1.77%\t+0.75%
11                   12\t13\t^\tMATLAB\t1.47%\t+0.28%
12                      13\t8\tvv\tPHP\t1.46%\t-0.09%
13                     14\t17\t^\tRust\t1.32%\t+0.35%
14                        15\t18\t^\tR\t1.20%\t+0.23%
15                     16\t19\t^\tRuby\t1.13%\t+0.18%
16                  17\t14\tv\tScratch\t1.11%\t+0.03%
17                   18\t20\t^\tKotlin\t1.10%\t+0.20%
18                    19\t21\t^\tCOBOL\t1.09%\t+0.22%
19                   20\t16\tvv\tSwift\t1.08%\t+0.09%

In [13]:
df = clean_tiobe_history(df)

In [14]:
df.query("language == 'SQL'")

    year language  rank
80  1987      SQL   NaN
79  1992      SQL   NaN
78  1997      SQL   NaN
77  2002      SQL   7.0
76  2007      SQL   NaN
75  2012      SQL   NaN
74  2017      SQL   NaN
73  2022      SQL   9.0
72  2024      SQL   8.0